#based on https://stackoverflow.com/questions/51809739/setting-up-travis-ci-with-cmake-c17-project/51812628#51812628
# License: CC BY-SA 3.0 https://creativecommons.org/licenses/by-sa/3.0/
#
language: cpp

matrix:
  - os: linux
    compiler: g++-7
    env: CXX=g++-7
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7

  - os: linux
    compiler: clang++-6.0
    env: CXX=clang++-6.0
    addons:
      apt:
        packages:
          - clang-6.0
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - make test
